[GLOBAL]
pants_version = "2.16.0"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = true
repo_id = "a888d69447a54a8892c9fe2cd1ea2ace"

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/"]

[python]
interpreter_constraints = [">=3.8"]
resolves = { python-default = "python-default.lock", flake8 = "flake8.lock", mypy = "mypy.lock"}
enable_resolves = true

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[flake8]
install_from_resolve = "flake8"

[mypy]
install_from_resolve = "mypy"

[docformatter]
args = ["--wrap-summaries=120", "--wrap-descriptions=120"]