[GLOBAL]
pants_version = "2.14.1"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = true
repo_id = "a888d69447a54a8892c9fe2cd1ea2ace"

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/"]

[python]
interpreter_constraints = [">=3.8,<3.11"]
resolves = { python-default = "python-default.lock"}

enable_resolves = true

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[flake8]
extra_requirements.add = [
  "flake8-tidy-imports",
  "flake8-annotations-coverage",
  "flake8-pytest-style",
  "flake8-bugbear",
  "flake8-pantsbuild",
  "flake8-absolute-import",
  "vulture"
]
lockfile = "flake8.lock"

[mypy]
extra_requirements.add = [
  "numpy"
]
extra_type_stubs = ["types-requests==2.28.11.8"]
lockfile = "mypy.lock"